export const siteConfig = {
  name: "AERBAVS",
  legalName: "AERBAVS MRO Parts & Leasing FZCO",
  tagline: "Supplying the Skies Since 2020",
  description:
    "AERBAVS MRO Parts & Leasing FZCO — Dubai-based aviation parts supplier and aircraft leasing company. Supplying the skies since 2020 with certified aircraft components, aviation consumables, tools, and leasing solutions from Dubai Silicon Oasis, UAE.",
  shortDescription:
    "Dubai-based aviation MRO parts supplier and aircraft leasing company. Serving airlines, MROs, and operators globally since 2020.",
  url: "https://www.aerbavs.com",
  ogImage: "/opengraph-image",
  foundedYear: "2020",
  links: {
    email: "info@aerbavs.com",
    emailSales: "sales@aerbavs.com",
    phone: "+971 54 176 1644",
    aog: "+971 54 176 1644",
    linkedin: "https://linkedin.com/company/aerbavs",
    twitter: "https://twitter.com/aerbavs",
  },
  locations: [
    {
      city: "Dubai",
      country: "UAE",
      address: "Building A1, Dubai Digital Park, Dubai Silicon Oasis, Dubai, UAE",
      mapUrl: "https://maps.google.com/?q=Dubai+Digital+Park+Dubai+Silicon+Oasis",
      isPrimary: true,
    },
  ],
  keywords: [
    "aviation parts supplier Dubai",
    "aircraft parts UAE",
    "MRO parts Dubai",
    "aviation consumables UAE",
    "aircraft engine parts supplier",
    "aviation tools supplier Dubai",
    "aircraft leasing UAE",
    "AOG support Dubai",
    "aviation supplier Dubai Silicon Oasis",
    "aerospace supply Middle East",
    "aviation parts Middle East",
    "aircraft consumables supplier",
    "avionics supplier UAE",
    "hangar supplies Dubai",
    "aviation lubricants UAE",
    "aviation adhesives sealants",
    "aircraft leasing support",
    "aviation MRO parts",
    "fleet support operations UAE",
    "defense aviation supply UAE",
  ],
} as const;
